spring.application.name=placas_db
spring.datasource.url=jdbc:postgresql://localhost:8081/placas_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
# Isso ajuda o Postgres a criar a tabela se ela não existir
spring.sql.init.mode=always